MyBlog/MyBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(url='/blog/', permanent=True)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MyBlog/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blogs/$', views.BlogListView.as_view(), name='blogs'),
    url(r'^bloggers/$', views.AuthorListView.as_view(), name='bloggers'),
    url(r'^blogs/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='blog-detail'),
    url(r'^blogs/(?P<pk>\d+)/comment/$', views.CommentCreate.as_view(), name='comment_create'),
    url(r'^bloggers/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

MyBlog/blog/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio here")

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return self.user.username


class Blog(models.Model):
    name = models.CharField(max_length=200, help_text="Blog's name")
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    text = models.TextField(max_length=500, help_text="Post text")
    date = models.DateField(default=date.today)

    class Meta:
        ordering = ["-date"]

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)
    text = models.TextField(max_length=1000, help_text="Enter  your comment")
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        len_title = 75
        if len(self.text) > len_title:
            titlestring = self.text[:len_title] + '...'
        else:
            titlestring = self.text
        return titlestring

MyBlog/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Author, Blog, Comment
from django.urls import reverse


# Create your views here.
def index(request):
    num_bloggers = Author.objects.all().count()
    num_posts = Blog.objects.all().count()
    num_comments = Comment.objects.all().count()
    return render(request, 'index.html', context={
                                        'num_bloggers': num_bloggers,
                                        'num_posts': num_posts,
                                        'num_comments': num_comments
                                        },)


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5


class AuthorListView(generic.ListView):
    model = Author


class BlogDetailView(generic.DetailView):
    model = Blog


class AuthorDetailView(generic.DetailView):
    model = Author 


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['text', ]

    def get_context_data(self, **kwargs):
        context = super(CommentCreate, self).get_context_data(**kwargs)
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return super(CommentCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'], })

MyBlog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Django Blog{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

      {% load static %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'bloggers' %}">All Bloggers</a></li>
                        <li><a href="{% url 'blogs' %}">All Blogs</a></li>
                        {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
                        {% endif %} 
                        </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10">
                <div class="content">
                    {% block content %}{% endblock %}
                </div>
                {% block pagination %}
                    {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                        </span>
                    </div>
                    {% endif %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

MyBlog/blog/templates/blog/author_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Blogger: {{ author.user.username }}</h1>
<h2>Bio: </h2>
<p>{{ author.bio }}</p>
<h2>Blogs List</h2>
<ul>
    {% if author.blog_set.all %}
        {% for blog in author.blog_set.all %}
            <li>
                <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{ blog.date }})
            </li>
        {% endfor %}
    {% else %}
    <p>This author did not publish any blogs yet</p>
    {% endif %}
</ul>
{% endblock %}

MyBlog/blog/templates/blog/author_list.html
{% extends 'base.html' %}

{% block content %}
    {% if author_list %}
    <h1>All Bloggers:</h1>
    <ul>
        {% for blogger in author_list %}
        <li><a href="{{ blogger.get_absolute_url }}">{{ blogger.user.username }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There is no bloggers(yet)</p>
    {% endif %}
{% endblock %}

MyBlog/blog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ blog.name }}</h1>
    <h3>Post Date <span>{{ blog.date }}</span></h3>
    <h3>Author: <span>{{ blog.author }}</span></h3>
    <h3>Description: </h3>
    <p>{{ blog.text }}</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    
    <div class="comments-section">
        <h4>Comments</h4>
        {% for comment in blog.comment_set.all %}
            <div class="comment">
                <p>{{ comment.author }} ({{ comment.post_date }}) - {{comment.text}}</p>
            </div>
        {% endfor %}
        <hr/>
        {% if user.is_authenticated %}
            <p><a href="{% url 'comment_create' blog.id %}">Leave</a> a comment</p>
        {% else %}
            <p><a href="{% url 'login' %}?next={{request.path}}">Login</a> to add new Comment</p>
        {% endif %}
    </div>
        

{% endblock %}

MyBlog/blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block content %}
    <h1>All blogs:</h1>
    {% if blog_list %}
    <ul>
        {% for blog in blog_list %}
            <li>
                <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{ blog.date }}) — {{ blog.author }}
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Sorry there are no blogs</p>
    {% endif %}
    
    
{% endblock %}

MyBlog/blog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

MyBlog/blog/templates/index.html
{% extends "base.html" %}

{% block title %}Django Blog Home{% endblock %}

{% block content %}
<div class="jumbotron text-center">
    <h1>Welcome to Simple blog powered by Django!</h1>
    <h2>Currently we have:</h2>
    <ul>
        <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
        <li><strong>Posts:</strong> {{ num_posts }}</li>
        <li><strong>Comments:</strong> {{ num_comments }}</li>
    </ul>
</div>

{% endblock %}